### ISSUE TITLE
Provide a restful API for node management?

### ISSUE THREAD

**Issue by rfk** [mozilla-services/wimms#2]
The current plan for fxa+sync involves deploying tokenserver and sync nodes into 
AWS.  Ops have expressed interest in automating as much of the node management as possible.  Simple example:  when a new storage node spins up in AWS, it could automatically register itself with the tokenserver and immediately become available for node allocation.

@tarekziade @ametaireau what do you think about morphing this into a stand-alone webservice with a restful node-management API, to more easily enable this kind of automation?

**Comment by almet** [comment]
To register a new node, there are a few things to be done:
- Agree on a secret between the tokenserver and the node. you can ask the tokenserver to generate this secret for you (there is a `generate-secret` script for this).
- Provision the node with this secret
- Create the node in WIMMS.

We can expose this via a REST service, but we also can do that using a script that should be ran by puppet (or salt, or whatever ops are using).

I'm a bit reluctant to exposing this thing to a REST endpoint (more power via HTTP sounds like something I would prefer to avoid), but I guess that's up to the ops to decide which way they prefer to head :)

**Comment by rfk** [comment]
This now lives directly in tokenserver, closing this out
